### ISSUE TITLE
License

### ISSUE THREAD

**Issue by abel-bzz** [stcorp/netcdf-compare#1]
Dear netcdf-compare maintainers,

We have few different tools in my organization that does netcdf to netcdf comparison and I would like to see how `netcdf-compare` compare to them. In the event it offers more features I would like to replace our tools with this one.

Unfortunately, there is no license at the moment in this repository.
Would it be possible to add an open source license on it ?
There a many choices among MIT, GPL, Apache2...

Also, I see that there was no commit for a long time, do you use something else to perform this kind task now ? 

Best regards.

**Comment by svniemeijer** [comment]
Happy to see that you are interested in this tool.
We are still using it internally. The fact that there haven't been any commits recently is because the tool is already doing what we want it to do. So it is in a rather stable state for us.

The license of the tool is the BSD 3-clause license, which we use for most of our other open source packages. It is referenced in the setup.py file, but I agree that we should make this more explicit. We will add a separate LICENSE file.

**Comment by svniemeijer** [comment]
The license file has been added

**Comment by srepmub** [comment]
of course please do let us know about any features that we could add :) (without making the tool very complex, as it is now nice and simple).

**Comment by abel-bzz** [comment]
Thanks !
One thing that could be nice is to publish netcdf-compare on pip and/or conda-forge.
Regarding features, I will let you know if I think about something useful once I'm more experienced with the package.
